name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build with Buildozer
      uses: maxim-lobanov/setup-buildozer@v6

    - name: Run Buildozer
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v6
      with:
        name: apk
        path: bin/*.apk
